version: '3'

services:
  app:
    container_name: ${CONTAINERS_PREFIX}-app
    build:
      context: ../containers/app
      args:
        NVM_VERSION: ${NVM_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        TIMEZONE: ${TIMEZONE}
    environment:
      - HOST=0.0.0.0
      - PORT=3035
    volumes:
      - ${APP_BACKEND_DIR}:/home/app/backend
      - ${APP_FRONTEND_DIR}:/home/app/frontend
      - ~/.ssh:/root/.ssh:ro
    ports:
      - 3003:3035
    stdin_open: true
    tty: true

  nginx:
    container_name: ${CONTAINERS_PREFIX}-nginx
    build:
      context: ../containers/nginx
      args:
        TIMEZONE: ${TIMEZONE}
    environment:
      APP_BACKEND_WEB_DIR: ${APP_BACKEND_WEB_DIR}
    ports:
      - 3002:80
      - 3001:3001
    volumes:
      - ../containers/nginx/nginx.conf:/etc/nginx/conf.d/default.template
      - ${APP_BACKEND_DIR}:/home/app/backend
      - ${APP_BACKEND_DIR}:/home/app/frontend
    command: /bin/bash -c "envsubst '$$APP_BACKEND_WEB_DIR $$APP_FRONTEND_WEB_DIR' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    links:
      - php

  php:
    container_name: ${CONTAINERS_PREFIX}-php
    build:
      context: ../containers/php7
      args:
        GID: ${GID}
        PHPREDIS_VERSION: ${PHPREDIS_VERSION}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_MACHINE_IP}
      PHP_IDE_CONFIG: serverName=${XDEBUG_IDE_SERVER_NAME}
    volumes:
      - ../containers/php7/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ../containers/php7/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ${APP_BACKEND_DIR}:/home/app/backend
    links:
      - redis

  redis:
    container_name: ${CONTAINERS_PREFIX}-redis
    image: redis:3

  postgres:
    container_name: ${CONTAINERS_PREFIX}-postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 55432:5432
    volumes:
      - ../persist-data/postgres:/var/lib/postgresql/data

#  mysql:
#    container_name: ${CONTAINERS_PREFIX}-mysql
#    image: mysql:${MYSQL_VERSION}
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#    ports:
#      - 8081:8080
#    volumes:
#      - ../persist-data/mysql:/var/lib/mysql

  adminer:
    container_name: ${CONTAINERS_PREFIX}-adminer
    image: adminer:${ADMINER_VERSION}
    ports:
      - 3004:8080

#  laravel-echo-server:
#    container_name: ${CONTAINERS_PREFIX}-laravel-echo-server
#    build:
#      context: ../containers/laravel-echo-server
#    links:
#      - redis
#    volumes:
#      - ../containers/laravel-echo-server/config.json:/home/laravel-echo-server/laravel-echo-server.json
#    ports:
#      - 6001:6001
#    links:
#      - redis
